### ISSUE TITLE
Usage in no_std environments

### ISSUE THREAD

**Issue by MathiasKoch** [00imvj00/mqttrs#21]
Would it be possible to allow usage in no_std environments?

`bytes` already supports disabling `std` through features, so it seems pretty trivial to add a feature gate to allow usage in no_std?

It seems like the only usage of std is
```
use std::{
    error::Error as ErrorTrait,
    fmt,
    io::{Error as IoError, ErrorKind},
    num::NonZeroU16,
};
```

`error` and `fmt` can be imported from `core` instead, `io::Error` seems to be a convenience implementation of From, that could be just feature gated in a no_std cfg..

The `NonZeroU16` I am a bit unsure of, but it should be pretty trivial?

**Comment by 00imvj00** [comment]
Sure i would like to explore in that. The primary use case was to build broker just for fun for me. 

But, if there is a use case, which there will be, i think this is a good opportunity to get started with it.

**Comment by 00imvj00** [comment]
I will surely look into that. and you are welcome opening PR also. :)

**Comment by MathiasKoch** [comment]
That sound great! I can do an initial PR, but i currently don't have the means to actually test the implementation any more than checking it will compile..
I am still just sweeping github for libraries that might be handy for my IoT application development, to get an idea of how much i have left to implement myself.

**Comment by 00imvj00** [comment]
ok. just open an initial PR, then we can take it from where it needs to be by testing and building on top of initial PR.

**Comment by MathiasKoch** [comment]
Sounds good! I will give it a go, as soon as i get some time.

**Comment by 00imvj00** [comment]
awesome. thank you.

**Comment by vincentdephily** [comment]
Looking forward to a no-std mqttrs :) I think it might even be possible without a feature flag, which would be great.

NonZeroU16 should be nostd-safe.

I don't quite recall what `std::fmt` is used for; if it's used for error handing then the best thing to do might be to tweak the error types a bit.

Concerning `bytes`, I'd like to loosen the dependency on it anyway, accepting an `Into<Buf>` or something even more generic. The `bytes` crate has changed its API since the `async.await` release, we should probably update to that, unless we want to keep our MSRV low. https://seanmonstar.com/post/189439210962/http-v02 mentions that they managed to keep using `Bytes` but don't expose it in the API anymore, we should have a look at how they did it.

The `bytes` work could probably be a PR on its own, separate of the no-std work. I'd get to it eventually, but not before end of 2020Q1.

**Comment by MathiasKoch** [comment]
Sounds great! @vincentdephily if you have the time before me, feel free to open an initial PR :)
