### ISSUE TITLE
New release on crates.io?

### ISSUE THREAD

**Issue by MathiasKoch** [00imvj00/mqttrs#24]
Could you maybe cut a new release on crates.io?

**Comment by vincentdephily** [comment]
I'd say we can release with the current feature set. I'm eager to stop using git versions in my Cargo.toml.

I've since updated my client to use the new mqttrs, so I no longer feel the need for a bytes-0.4 vs bytes-0.5. We can always revisit that if/when the need arises, but my guess is that the demand for byte-0.4 is disappearing quickly.

I didn't get time to play with the no_std feature, but it looks fine. @MathiasKoch could you do the documentation/metadata side of that feature ? I think that's all that's needed for a clean release.

- Add an entry to Changelog.md
- Add a std section in README.md (like the serde section) mentioning the existence of the feature and what APIs you give up on by disabling it.
- Add "no-std" to Cargo.toml.package.categories
- Add yourself to Cargo.toml.package.authors (if you want)

**Comment by vincentdephily** [comment]
The 0.3.0 release is out on crates.io and github. Thank @MathiasKoch for the no_std work and @00imvj00 for giving me write access to do the release.
